### ISSUE TITLE
Procura por duplicados no índice de LILACS_Sas_Sources indica erro no algoritmo

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/NGrams#11]
@viniciusandrade  relatou a não recuperação de um documento sabidamente duplicado no índice.

**Comment by heitorbarbieri** [comment]
Corrigido no commit 9c180ff

**Comment by viniciusandrade** [comment]
Seguem dados que evidenciam o comportamento para documentar:

titulo_revista: **Rev. cuba. pediatr**
volume_fasciculo: **92**
numero_fasciculo: **1**

Não recupera nenhum registro fonte. Ao adicionar o parâmentro ISSN: **0034-7531**  recupera outros registros fonte desta revista com similiaridade de 1.0 mas nenhum resultado para volume 92 e fascículo 1.

Obrigado
